// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR-sY_JAbaVIo5CFykbeeZCFFcGFzxg38',
    appId: '1:436838832758:web:739ac0f800d153f8239d57',
    messagingSenderId: '436838832758',
    projectId: 'wardrobeai-d3f40',
    authDomain: 'wardrobeai-d3f40.firebaseapp.com',
    storageBucket: 'wardrobeai-d3f40.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyGuRm-9mskVVi182mVp6SwWObnpVAFYg',
    appId: '1:436838832758:android:c07ba4819082c92f239d57',
    messagingSenderId: '436838832758',
    projectId: 'wardrobeai-d3f40',
    storageBucket: 'wardrobeai-d3f40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ-sjipn98qcN7B-rMsgMPAVRfZHZclkA',
    appId: '1:436838832758:ios:4e5e414b9da013d8239d57',
    messagingSenderId: '436838832758',
    projectId: 'wardrobeai-d3f40',
    storageBucket: 'wardrobeai-d3f40.firebasestorage.app',
    iosBundleId: 'com.example.wardrobeAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ-sjipn98qcN7B-rMsgMPAVRfZHZclkA',
    appId: '1:436838832758:ios:4e5e414b9da013d8239d57',
    messagingSenderId: '436838832758',
    projectId: 'wardrobeai-d3f40',
    storageBucket: 'wardrobeai-d3f40.firebasestorage.app',
    iosBundleId: 'com.example.wardrobeAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR-sY_JAbaVIo5CFykbeeZCFFcGFzxg38',
    appId: '1:436838832758:web:2a445c4789121007239d57',
    messagingSenderId: '436838832758',
    projectId: 'wardrobeai-d3f40',
    authDomain: 'wardrobeai-d3f40.firebaseapp.com',
    storageBucket: 'wardrobeai-d3f40.firebasestorage.app',
  );
}
